apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "refit-ai.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "refit-ai.labels" . | nindent 4 }}
spec:
  strategy:
    {{- toYaml .Values.deploymentStrategy | nindent 4 }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "refit-ai.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "refit-ai.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "refit-ai.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ include "refit-ai.appSecretName" . }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.uploadVolume.enabled }}
          volumeMounts:
            - name: upload-volume
              mountPath: {{ .Values.uploadVolume.mountPath }}
          {{- end }}
      {{- if .Values.uploadVolume.enabled }}
      volumes:
        - name: upload-volume
          emptyDir: {}
      {{- end }}
